### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by Xendomn** [liu-mengyang/rust-mmdeploy#4]
![image](https://user-images.githubusercontent.com/42320071/200459647-dbc9dea1-dd1a-4600-bda9-290cfac92b21.png)    
    
画圈的地方，好像多个sdk路径

**Comment by liu-mengyang** [comment]
`sdk` directory is existing under the released package of MMDeploy from the link I give. Please check again.

**Comment by liu-mengyang** [comment]
Hi! I think that this issue has been solved and I will close it. Please feel free to open it again if you still has any questions.
