### ISSUE TITLE
Specifying 'device' field of mmdeploy_mat_t in rust API and C API will cause opencv resize error in mmdeploy>=0.10.0

### ISSUE THREAD

**Issue by XWHtorrentx** [liu-mengyang/rust-mmdeploy#5]
I have posted this issue on the following page
https://github.com/open-mmlab/mmdeploy/issues/1710

**Comment by liu-mengyang** [comment]
Thanks for your feedback. This is a known error for using this repo with mmdeploy>=0.10.0. Just fix this error is not a problem. But I need time to make sure the new version of rust-mmdeploy can perform well together with the latest mmdeploy.

Please forgive me that if you want to avoid this error, mmdeploy==0.9.0 is the only method now.
I am trying to update this repo to match the latest mmdeploy.

**Comment by XWHtorrentx** [comment]
Thanks for your reply. I have been working on this problem for two days. I would like to share some opinions with you if you dont mind.
I think this has something to do with the constructor of mat, which is overloaded with default device (but I didnt dig further how this default device is chosen). If there is a workaround, it must be some implementation of constructor of mat in rust, which can be a little bit tricky because there is no constructor in rust at all.

**Comment by XWHtorrentx** [comment]
I guess it has nothing to do with the rust API buildup. My colleague used pure C API and Python API, then had the same problem as I did.
